Repository scimmyjs/scimmy, pull requests merged in 2025-02, with the labels that each got.

#69 Add `schemas` in `SCIMMY.Messages.PatchOp` documentation and typing
  src/lib/messages/patchop.js
  src/lib/types/resource.js
  test/lib/messages/patchop.js
Labels: documentation

#71 Add `totalResults` parameter to `SCIMMY.Messages.ListResponse` constructor
  src/lib/messages/listresponse.js
  test/lib/messages/listresponse.js
Labels: documentation, feature

#72 Add schema ID static get accessor properties for all `SCIMMY.Messages` classes
  src/lib/messages/bulkrequest.js
  src/lib/messages/bulkresponse.js
  src/lib/messages/error.js
  src/lib/messages/listresponse.js
  src/lib/messages/patchop.js
  src/lib/messages/searchrequest.js
  test/lib/messages/bulkrequest.js
  test/lib/messages/bulkresponse.js
  test/lib/messages/error.js
  test/lib/messages/listresponse.js
  test/lib/messages/searchrequest.js
Labels: documentation, feature

#75 Make return type of `attribute` method generic in `SCIMMY.Types.SchemaDefinition` class
  src/lib/types/definition.js
Labels: bug, documentation

#76 Update direction of `externalId` attribute to default value of "both"
  src/lib/types/definition.js
Labels: bug
